Repository Harrison-Huang666/COMP30022-49, pull requests merged in 2021-10, with the labels that each got.

#14 Create contact by user name
  controller/contactController.js
  routes/contactRouter.js
Labels: enhancement

#25 added title text for REST_PASSWORD api && change the base url from lo…
  src/API/restPassword/Reset.js
Labels: enhancement

#27 Update contact page css
  package-lock.json
  package.json
  src/API/contact/Contact.js
  src/API/contact/People.jsx
  src/API/contact/Person.jsx
  src/API/contact/contact.css
  src/API/record/AddRecord.js
Labels: enhancement

#43 Week 11 TODO
  src/API/contact/contact.css
  src/API/contact/editContact.css
  src/API/person/Person1.js
  src/API/person/person.css
  src/API/person/qr.js
  src/API/record/recordDetail.js
  src/index.css
Labels: enhancement, contact, personal information, frontend, demo, profile, QR code

#45 Image upload & Set Avatar
  src/API/contact/People.jsx
  src/API/fileUpload/FileUpload.js
  src/API/fileUpload/Message.js
  src/API/fileUpload/Progress.js
  src/API/person/Person.js
  src/App.js
Labels: enhancement, personal information, frontend, profile, image

#44 update displayImage return content type
  config/upload.js
  controller/contactController.js
  controller/profileController.js
  models/userSchema.js
  routes/profileRouter.js
Labels: enhancement, backend, contact, frontend, test, api, image
